// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGI6dhfv6h98dyB8xF796VhclUc-O3g9w',
    appId: '1:1007906131899:web:ffd82500367f631b8cfe9e',
    messagingSenderId: '1007906131899',
    projectId: 'movie-1-a3ff3',
    authDomain: 'movie-1-a3ff3.firebaseapp.com',
    storageBucket: 'movie-1-a3ff3.appspot.com',
    measurementId: 'G-9JN30ZE95M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDWeQvqfX4uk3Q1QFTF4fsKdLq_o0Gf2E',
    appId: '1:1007906131899:android:bfa91fc724ed1ba98cfe9e',
    messagingSenderId: '1007906131899',
    projectId: 'movie-1-a3ff3',
    storageBucket: 'movie-1-a3ff3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb4eru7zRVCTzrcI25hndyOp925VTqoNs',
    appId: '1:1007906131899:ios:704c76e0551cd5908cfe9e',
    messagingSenderId: '1007906131899',
    projectId: 'movie-1-a3ff3',
    storageBucket: 'movie-1-a3ff3.appspot.com',
    iosClientId: '1007906131899-hq5b51hl0b12umvmn3fsq6p6i89fkkbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb4eru7zRVCTzrcI25hndyOp925VTqoNs',
    appId: '1:1007906131899:ios:704c76e0551cd5908cfe9e',
    messagingSenderId: '1007906131899',
    projectId: 'movie-1-a3ff3',
    storageBucket: 'movie-1-a3ff3.appspot.com',
    iosClientId: '1007906131899-hq5b51hl0b12umvmn3fsq6p6i89fkkbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMovie',
  );
}
